version: '3'
services:
  local-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my_postgres_db
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
