// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	models "bulletin-board-api/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "bulletin-board-api/internal/repository"
)

// AddressRepository is an autogenerated mock type for the AddressRepository type
type AddressRepository struct {
	mock.Mock
}

// CountEmptyVaspUUID provides a mock function with given fields: ctx
func (_m *AddressRepository) CountEmptyVaspUUID(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountEmptyVaspUUID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOneOwnership provides a mock function with given fields: ctx, ownership
func (_m *AddressRepository) CreateOneOwnership(ctx context.Context, ownership *models.AddressOwnership) error {
	ret := _m.Called(ctx, ownership)

	if len(ret) == 0 {
		panic("no return value specified for CreateOneOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AddressOwnership) error); ok {
		r0 = rf(ctx, ownership)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOne provides a mock function with given fields: ctx, proof
func (_m *AddressRepository) DeleteOne(ctx context.Context, proof *models.AddressOwnershipProof) error {
	ret := _m.Called(ctx, proof)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AddressOwnershipProof) error); ok {
		r0 = rf(ctx, proof)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEmptyVaspUUID provides a mock function with given fields: ctx, limit
func (_m *AddressRepository) FindByEmptyVaspUUID(ctx context.Context, limit int) ([]*models.AddressOwnershipProof, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmptyVaspUUID")
	}

	var r0 []*models.AddressOwnershipProof
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*models.AddressOwnershipProof, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.AddressOwnershipProof); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AddressOwnershipProof)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOne provides a mock function with given fields: ctx, request
func (_m *AddressRepository) GetOne(ctx context.Context, request *repository.AddressRepoGetRequest) (*models.AddressOwnershipProof, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetOne")
	}

	var r0 *models.AddressOwnershipProof
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.AddressRepoGetRequest) (*models.AddressOwnershipProof, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.AddressRepoGetRequest) *models.AddressOwnershipProof); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AddressOwnershipProof)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.AddressRepoGetRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOne provides a mock function with given fields: ctx, proof
func (_m *AddressRepository) UpdateOne(ctx context.Context, proof *models.AddressOwnershipProof) error {
	ret := _m.Called(ctx, proof)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AddressOwnershipProof) error); ok {
		r0 = rf(ctx, proof)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOwnership provides a mock function with given fields: _a0, proof
func (_m *AddressRepository) UpdateOwnership(_a0 context.Context, proof *models.AddressOwnershipProof) error {
	ret := _m.Called(_a0, proof)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AddressOwnershipProof) error); ok {
		r0 = rf(_a0, proof)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAddressRepository creates a new instance of AddressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressRepository {
	mock := &AddressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
