// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	models "bulletin-board-api/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VaspRepository is an autogenerated mock type for the VaspRepository type
type VaspRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, vaspID
func (_m *VaspRepository) Get(ctx context.Context, vaspID uuid.UUID) *models.VASP {
	ret := _m.Called(ctx, vaspID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.VASP
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.VASP); ok {
		r0 = rf(ctx, vaspID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VASP)
		}
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *VaspRepository) GetAll(ctx context.Context) map[string]*models.VASP {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]*models.VASP
	if rf, ok := ret.Get(0).(func(context.Context) map[string]*models.VASP); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*models.VASP)
		}
	}

	return r0
}

// GetByDomain provides a mock function with given fields: ctx, domain
func (_m *VaspRepository) GetByDomain(ctx context.Context, domain string) *models.VASP {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetByDomain")
	}

	var r0 *models.VASP
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.VASP); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VASP)
		}
	}

	return r0
}

// NewVaspRepository creates a new instance of VaspRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVaspRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VaspRepository {
	mock := &VaspRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
