services:
  bbapisvc:
    containers:
      bbapi_dbmigrate:
        resources:
          limits:
            memory: 5000M
          requests:
            cpu: 1000m
            memory: 5000M
        image: travel-rule/bulletin-board-api/bbapisvc
      bbapi_metrics_reporter:
        resources:
          limits:
            memory: 5000M
          requests:
            cpu: 1000m
            memory: 5000M
        image: travel-rule/bulletin-board-api/bbapisvc
      bbapisvc:
        resources:
          limits:
            memory: 5000M
          requests:
            cpu: 1000m
            memory: 5000M
        image: travel-rule/bulletin-board-api/bbapisvc
      nginx_sidecar:
        resources:
          limits:
            memory: 5000M
          requests:
            cpu: 1000m
            memory: 5000M
        image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/travel-rule/nginx-sidecar@sha256:8fcd580a1ad856d05541a907653405c82b67c62b3c7bfe93299bae4f411a13b0
    target_group_bindings:
      api: bbapi-nlb-k8s-bbapisvc-k8s-produ
    scaling:
      min: 10
      max: 25
      targetcpu: 80
shared_env:
  BBAPI_ADDRESS_SECRET: config_service_secret://travel-rule/bulletin-board-api-production/bbapi-address-secret
  BBAPI_DB_URL: config_service_secret://travel-rule/bulletin-board-api-production/bbapi-db-url
  BBAPI_DB_READ_URL: config_service_secret://travel-rule/bulletin-board-api-production/bbapi-db-read-url
  BBAPI_KMS_KEY_ID: config_service_secret://travel-rule/bulletin-board-api-production/bbapi-kms-key-id
  BBAPI_STAGE: config_service_text://travel-rule/bulletin-board-api-production/bbapi-stage
  BBAPI_CERT_BUNDLE: config_service_secret://travel-rule/bulletin-board-api-production/ottr-certificate-api-trust-global-2025-07-31t16_48_20z
  BURST: config_service_text://travel-rule/bulletin-board-api-production/burst
  CA_CERT: config_service_secret://travel-rule/bulletin-board-api-production/ca-cert
  CLIENT_OCSP: config_service_text://travel-rule/bulletin-board-api-production/client-ocsp
  DB_HOST: config_service_secret://travel-rule/bulletin-board-api-production/db-host
  DB_IDENTIFIER: config_service_secret://travel-rule/bulletin-board-api-production/db-identifier
  DELAY: config_service_text://travel-rule/bulletin-board-api-production/delay
  HEALTH_CHECK_LISTEN_PORT: config_service_text://travel-rule/bulletin-board-api-production/health-check-listen-port
  HEALTH_CHECK_TARGET_PORT: config_service_text://travel-rule/bulletin-board-api-production/health-check-target-port
  LIMITING_RATE_PER_SECOND: config_service_text://travel-rule/bulletin-board-api-production/limiting-rate-per-second
  NGINX_LOG_LEVEL: config_service_text://travel-rule/bulletin-board-api-production/nginx-log-level
  SERVER_CERT: config_service_secret://travel-rule/bulletin-board-api-production/server-cert
  SERVER_KEY: config_service_secret://travel-rule/bulletin-board-api-production/server-key
  SERVER_OCSP_STAPLING: config_service_text://travel-rule/bulletin-board-api-production/server-ocsp-stapling
  SERVICE_ENV: config_service_text://travel-rule/bulletin-board-api-production/service-env
  SSL_LISTEN_PORT: config_service_text://travel-rule/bulletin-board-api-production/ssl-listen-port
  TARGET_HOSTNAME: config_service_text://travel-rule/bulletin-board-api-production/target-hostname
  TARGET_PORT: config_service_text://travel-rule/bulletin-board-api-production/target-port
  TARGET_PROTOCOL: config_service_text://travel-rule/bulletin-board-api-production/target-protocol
  TOOLKIT_PASS: config_service_secret://travel-rule/bulletin-board-api-production/toolkit-pass
  TOOLKIT_USER: config_service_text://travel-rule/bulletin-board-api-production/toolkit-user
