// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	service "bulletin-board-api/internal/service"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AddressService is an autogenerated mock type for the AddressService type
type AddressService struct {
	mock.Mock
}

// CreateAddressOwnership provides a mock function with given fields: ctx, request
func (_m *AddressService) CreateAddressOwnership(ctx context.Context, request *service.CreateAddressOwnershipRequest) (*service.CreateAddressOwnershipResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *service.CreateAddressOwnershipResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service.CreateAddressOwnershipRequest) *service.CreateAddressOwnershipResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CreateAddressOwnershipResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service.CreateAddressOwnershipRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAddressOwnership provides a mock function with given fields: ctx, address, chain
func (_m *AddressService) DeleteAddressOwnership(ctx context.Context, address string, chain string) error {
	ret := _m.Called(ctx, address, chain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, address, chain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAddressOwnership provides a mock function with given fields: ctx, address, chain
func (_m *AddressService) GetAddressOwnership(ctx context.Context, address string, chain string) (*service.GetAddressOwnershipResponse, error) {
	ret := _m.Called(ctx, address, chain)

	var r0 *service.GetAddressOwnershipResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *service.GetAddressOwnershipResponse); ok {
		r0 = rf(ctx, address, chain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.GetAddressOwnershipResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, address, chain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAddressOwnershipProof provides a mock function with given fields: ctx, request
func (_m *AddressService) UpdateAddressOwnershipProof(ctx context.Context, request *service.UpdateAddressOwnershipProofRequest) (*service.UpdateAddressOwnershipProofResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *service.UpdateAddressOwnershipProofResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service.UpdateAddressOwnershipProofRequest) *service.UpdateAddressOwnershipProofResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UpdateAddressOwnershipProofResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service.UpdateAddressOwnershipProofRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
