// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	models "bulletin-board-api/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VaspService is an autogenerated mock type for the VaspService type
type VaspService struct {
	mock.Mock
}

// GetVasp provides a mock function with given fields: ctx, vaspID
func (_m *VaspService) GetVasp(ctx context.Context, vaspID uuid.UUID) (*models.VASP, error) {
	ret := _m.Called(ctx, vaspID)

	var r0 *models.VASP
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.VASP); ok {
		r0 = rf(ctx, vaspID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VASP)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, vaspID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVasps provides a mock function with given fields: ctx
func (_m *VaspService) GetVasps(ctx context.Context) (map[string]*models.VASP, error) {
	ret := _m.Called(ctx)

	var r0 map[string]*models.VASP
	if rf, ok := ret.Get(0).(func(context.Context) map[string]*models.VASP); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*models.VASP)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchVasp provides a mock function with given fields: ctx, domain
func (_m *VaspService) SearchVasp(ctx context.Context, domain string) (*models.VASP, error) {
	ret := _m.Called(ctx, domain)

	var r0 *models.VASP
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.VASP); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VASP)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
