package constants

type RequestVASPCtxKey struct{}

type RequestIDCtxkey struct{}

const (
	RequestVASPHeaderKey          = "X-VASP-DNS-NAME"
	RequestRequestIDHeaderKey     = "X-REQUEST-ID"
	RequestVaspLoggingIDHeaderKey = "X-VASP-LOGGING-ID"
	BulletinBoardServiceName      = "bulletin-board-api"
	Base64EncodedSaltStringTest   = "D2R5WSpZZyj0RSw1F7HrLVDxZX3nrX4Xb6+ce4qX6H21y8bRqtq/S3SNYdL5NJ0bHY/uPO5DOjl0XJaNRKXRsg=="
)

const (
	// chains with address ownership proof supports.
	ChainBitcoin         = "BITCOIN"
	ChainEthereum        = "ETHEREUM"
	ChainSolana          = "SOLANA"
	ChainRipple          = "RIPPLE"
	ChainLiteCoin        = "LITECOIN"
	ChainStellar         = "STELLAR"
	ChainCronos          = "CRONOS"
	ChainAvalancheCChain = "AVALANCHE_C_CHAIN"
	ChainAvalanchePChain = "AVALANCHE_P_CHAIN"
	ChainAvalancheXChain = "AVALANCHE_X_CHAIN"
	ChainBitcoinCash     = "BITCOINCASH"
	ChainTron            = "TRON"
	ChainFilecoin        = "FILECOIN"
	ChainArbitrum        = "ARBITRUM"
	ChainNear            = "NEAR"
	ChainCelo            = "CELO"
	ChainAxelar          = "AXELAR"
	ChainPolygonPOS      = "POLYGON_POS"
	ChainCosmos          = "COSMOS"
	ChainAptos           = "APTOS"
	ChainPolkadot        = "POLKADOT"
	ChainCardano         = "CARDANO"
	ChainBase            = "BASE"
	ChainDogeCoin        = "DOGECOIN"
	ChainDash            = "DASH"
	ChainDfinity         = "DFINITY"
	ChainAlgorand        = "ALGORAND"
	ChainEosio           = "EOSIO"
	ChainTezos           = "TEZOS"
	ChainTon             = "TON"
	ChainBsc             = "BSC"
	ChainOptimism        = "OPTIMISM"
	ChainEthereumClassic = "ETHEREUMCLASSIC"
	ChainSui             = "SUI"
	ChainHedera          = "HEDERA"
	ChainSei             = "SEI"
	ChainHyperliquid     = "HYPERLIQUID"
	ChainMonad           = "MONAD"
	ChainArc             = "ARC"
	// address proof types.
	BitcoinP2PKH       = "BITCOIN_P2PKH"
	BitcoinP2SH        = "BITCOIN_P2SH"
	BitcoinP2SHP2WPKH  = "BITCOIN_P2SH_P2WPKH"
	BitcoinP2SHP2WSH   = "BITCOIN_P2SH_P2WSH"
	BitcoinP2WPKH      = "BITCOIN_P2WPKH"
	BitcoinP2WSH       = "BITCOIN_P2WSH"
	BitcoinP2L         = "BITCOIN_P2L"
	BitcoinP2TR        = "BITCOIN_P2TR"
	EthereumEOA        = "ETHEREUM_EOA"
	EthereumContract   = "ETHEREUM_CONTRACT"
	SolanaEd25519      = "SOLANA_ED25519"
	SolanaPda          = "SOLANA_PDA"
	RippleClassic      = "RIPPLE_CLASSIC"
	LitecoinP2PKH      = "LITECOIN_P2PKH"
	LitecoinP2WPKH     = "LITECOIN_P2WPKH"
	LitecoinP2SH       = "LITECOIN_P2SH"
	LitecoinP2WSH      = "LITECOIN_P2WSH"
	LitecoinP2SHP2WPKH = "LITECOIN_P2SH_P2WPKH"
	LitecoinP2SHP2WSH  = "LITECOIN_P2SH_P2WSH"
	LitecoinP2L        = "LITECOIN_P2L"
	StellarAccount     = "STELLAR_ACCOUNT"
	EvmEOA             = "EVM_EOA"
	EvmContract        = "EVM_CONTRACT"
	AvalancheAccount   = "AVALANCHE_ADDRESS"
	BitcoinCashP2PKH   = "BITCOINCASH_P2PKH"
	BitcoinCashP2SH    = "BITCOINCASH_P2SH"
	TronEOA            = "TRON_EOA"
	FilecoinBLS        = "FILECOIN_BLS"
	FilecoinECDSA      = "FILECOIN_ECDSA"
	NearImplicit       = "NEAR_IMPLICIT"
	NearNamed          = "NEAR_NAMED"
	CosmosSecp256k1    = "COSMOS_SECP256K1"
	CosmosSecp256r1    = "COSMOS_SECP256R1"
	AptosECDSA         = "APTOS_ECDSA"
	AptosEd25519       = "APTOS_ED25519"
	AptosMultiEd25519  = "APTOS_MULTI_ED25519"
	AptosMinpkbls      = "APTOS_MINPK_BLS"
	AptosMinSigbls     = "APTOS_MINSIG_BLS"
	PolkadotECDSA      = "POLKADOT_ECDSA"
	PolkadotEd25519    = "POLKADOT_ED25519"
	PolkadotSr25519    = "POLKADOT_SR25519"
	CardanoBase        = "CARDANO_BASE"
	CardanoPointer     = "CARDANO_POINTER"
	CardanoEnterprise  = "CARDANO_ENTERPRISE"
	CardanoReward      = "CARDANO_REWARD"
	CardanoByron       = "CARDANO_BYRON"
	DogecoinP2PKH      = "DOGECOIN_P2PKH"
	DogecoinP2SH       = "DOGECOIN_P2SH"
	DashP2PKH          = "DASH_P2PKH"
	DashP2SH           = "DASH_P2SH"
	DfinitySecp256k1   = "DFINITY_SECP256K1"
	DfinitySecp256r1   = "DFINITY_SECP256R1"
	DfinityEd25519     = "DFINITY_ED25519"
	AlgorandEd25519    = "ALGORAND_ED25519"
	EosioAll           = "EOSIO_ALL"
	TezosEd25519       = "TEZOS_ED25519"
	TezosSecp256k1     = "TEZOS_SECP256K1"
	TezosSecp256r1     = "TEZOS_SECP256R1"
	TonEd25519         = "TON_ED25519"
	EthereumClassicEOA = "ETHEREUMCLASSIC_EOA"
	SuiEd25519         = "SUI_ED25519"
	HederaEd25519      = "HEDERA_ED25519"
	SeiSecp256k1       = "SEI_SECP256K1"
	TronContract       = "TRON_CONTRACT"
	// auxProofData types.
	EthCreate   = "ETH_CREATE"
	EthCreate2  = "ETH_CREATE2"
	EthAllow    = "ETH_ALLOW"
	TronCreate  = "TRON_CREATE"
	TronCreate2 = "TRON_CREATE2"
	TronAllow   = "TRON_ALLOW"

	RedeemScript  = "REDEEM_SCRIPT"
	WitnessScript = "WITNESS_SCRIPT"

	// auxProofData data item keys.
	Nonce              = "nonce"
	Salt               = "salt"
	InitCodeHash       = "init_code_hash"
	Script             = "script"
	ClaimAddress       = "claim_address"
	EncryptedProgramID = "encryptedProgramId"
	EncryptedSeeds     = "encryptedSeeds"
	EncryptedPublicKey = "encryptedPublicKey"
)

var (
	StageProduction  = "production"
	StagePreprod     = "preprod"
	StageDevelopment = "development"
	StageLocal       = "local"

	AddressSecret = "ADDRESS_SECRET"

	//
	RedeemScriptValidDataType = []string{Script}
	EthCreateValidDataType    = []string{Nonce}
	EthCreate2ValidDataType   = []string{Salt, InitCodeHash}
	EthAllowValidDataType     = []string{ClaimAddress}
	TronCreateValidDataType   = []string{Nonce}
	TronCreate2ValidDataType  = []string{Salt, InitCodeHash}
	TronAllowValidDataType    = []string{ClaimAddress}
)
